#!/usr/bin/env node

const themes = require("./themes.js");
const fs = require("fs");
const path = require("path");
const distDir = path.resolve(process.cwd(), 'dist');

const themesJSON = JSON.stringify(themes, null, 2);

/* Create a JSON file. */
fs.writeFileSync(path.resolve(distDir, "themes.json"), themesJSON);