#!/usr/bin/env node

const themes = require("./themes.js");
const fs = require("fs");
const path = require("path");
const distDir = path.resolve(process.cwd(), "dist");
const createCSSVariablesFromObject = require("./src/createCSSVariablesFromObject");

const themesJSON = JSON.stringify(themes, null, 2);

/* Create a JSON file. */
fs.writeFileSync(path.resolve(distDir, "themes.json"), themesJSON);

/* Create a CSS file. */
const themesCSS = createCSSVariablesFromObject(themes, "--");
fs.writeFileSync(path.resolve(distDir, "themes.css"), `:root {${themesCSS}}`);

/* Create a SASS file. */
const themesSASS = createCSSVariablesFromObject(themes, "$");
fs.writeFileSync(path.resolve(distDir, "themes.scss"), `${themesSASS}`);
